major refactor
- add test, swap and backup files to .gitignore

- update ChangeLogs

- strip vimpager of uuencoded files and the uudecode function on `make
  install` and install runtime to PREFIX/share/vimpager, this is done
  with sed in the Makefile

- balance shell control statements with `: end*` statements for vimcat
  from the Makefile . This is done with the scripts/balance-vimcat
  script.

- make the bundling awk code in Makefile compatible with oawk by
  escaping forward slashes in file names with sed

- quote all file names in the Makefile

- fix list of docs installed to PREFIX/share/doc/vimpager in the
  Makefile

- add `scriptencoding utf-8` and set cpo in all vim scripts

- read pre-processing %.vim code on BufReadPost instead of BufWinEnter
  so that there is less flicker when loading the file

- less.vim now detects has('vim_starting') and does not turn on less
  mode in that case, also `g:less.enabled` is not set at all by
  default, this allows loading less.vim with `runtime macros/less.vim`
  from `.vimrc` safely

- delete empty buffer on vimpager startup since we are using `:args`
  instead of actual file args

- add a GUIInit() function called from vimpager#Init() that increases
  columsn for docs and writes the gvim_done file that vimpager waits
  for, used when `g:vimpager.gvim` is set.

- turn on mouse and clipboard support from vimpager#Init() by default
  by setting mouse=a ttymouse=xterm2 and clipboard=autoselect

- fix the line numbers option for vimpager

- fix Vim 7.3 compatibility by changing how the `g:less.statusfunc`
  funcref is handled. 7.3 does not allow funcrefs to s:Foo() funcs to be
  called from other scripts, and has no partial funcrefs, use autoload
  funcrefs and wrapper functions to get around this

- move utility functions to autoload/vimpager_utils.vim

- add support for Surround by adding the <nowait> tag to less.vim
  mappings on vim 7.4+. On Vim 7.3 still disable Surround.

- update debian/ for doc list and new scripts

- add docs for Pathogen installation

- add info on `g:mapleader` to docs

- use section links in the vimpager.md markdown

- add the Page command in plugin/vimpager.vim and the Less command in
  less.vim. They are mostly identical except that Page can call the
  vimpager_utils#ConcealRetab() function for files using AnsiEsc.

- add a "USING FROM VIM" section to docs with info on the Page command
  and how to load and use less.vim from vimrc

- remove argv checking from less.vim, that can be done in less.sh

- only define OptionSet auto commands if the event is available (not
  available on 7.3)

- improve the status line function in less.vim

- change the `q` mapping to close only the current buffer, or quit vim
  for the last buffer

- show mapleader in help and status line

- rewrite pass through mode in awk with multiple file support with
  separators

- add a seq function in awk for systems without seq like Solaris

- display usage if there are no args and no file on stdin for both
  vimpager and vimcat

- make usage output much faster

- add preliminary support for Ruby ri docs

- improve regexes for deteching man/perldoc/pydoc/ri

- check for gsed or /usr/bin/xpg4/sed when calling sed

- make grep_q work with oawk

- add line_n function

- lots of code cleanup and other misc. improvements

diff --git a/vimcat b/vimcat
--- a/vimcat
+++ b/vimcat
@@ -49,33 +49,6 @@
 
   # hopefully we're now POSIX, and shell is saved in ${_MY_SHELL}
 
-  tmp_dir=/tmp
-  mkdir_options="-m 700"
-
-  case "$(uname -s)" in
-    MINGW*|MSYS*)
-      if [ -n "${temp}" ]; then
-        # MSYS2 is a little tricky, we're gonna stick to the user's private temp
-        # the -m mode switch to mkdir doesn't work
-        tmp_dir="$(cygpath --unix "${temp}")"
-        mkdir_options=""
-      fi
-    ;;
-  esac
-
-  tmp_dir="${tmp_dir}/vimcat_${$}"
-
-  if ! mkdir ${mkdir_options} "${tmp_dir}"; then
-    echo "Could not create temporary directory ${tmp_dir}" >&2
-    exit 1
-  fi 
-
-  trap "rm -rf ${tmp_dir}" HUP INT QUIT ILL TRAP KILL BUS TERM
-  tmp_file_in="${tmp_dir}/vimcat_in.txt"
-  tmp_file_out="${tmp_dir}/vimcat_out.txt"
-
-  script="$(command -v ${0})"
-
 quit() {
   rm -rf "${tmp_dir}"
   exit "${@}"
@@ -105,13 +78,52 @@ or available locally via: [32mman [1;35mvimcat[0m
 EOF
 }
 
-  # check for arguments
-  while [ "${#}" -gt 0 ] ; do
-    case "${1}" in
-      '-h'|'--help'|'-help'|'--usage'|'-usage')
+  # if no args and no stdin, display usage
+  if [ "${#}" -eq 0 -a -t 0 ]; then
+    usage
+    quit 0
+  fi
+
+  # check for -h before main option parsing, this is much faster
+  for arg in "${@}"; do
+    case "${@}" in
+      "-h"|"--help"|"-help"|"--usage"|"-usage")
         usage
         quit 0
         ;;
+    esac
+  done
+
+  tmp_dir=/tmp
+  mkdir_options="-m 700"
+
+  case "$(uname -s)" in
+    MINGW*|MSYS*)
+      if [ -n "${temp}" ]; then
+        # MSYS2 is a little tricky, we're gonna stick to the user's private temp
+        # the -m mode switch to mkdir doesn't work
+        tmp_dir="$(cygpath --unix "${temp}")"
+        mkdir_options=""
+      fi
+    ;;
+  esac
+
+  tmp_dir="${tmp_dir}/vimcat_${$}"
+
+  if ! mkdir ${mkdir_options} "${tmp_dir}"; then
+    echo "Could not create temporary directory ${tmp_dir}" >&2
+    exit 1
+  fi
+
+  trap "rm -rf ${tmp_dir}" HUP INT QUIT ILL TRAP KILL BUS TERM
+  tmp_file_in="${tmp_dir}/vimcat_in.txt"
+  tmp_file_out="${tmp_dir}/vimcat_out.txt"
+
+  script="$(command -v ${0})"
+
+  # check for arguments
+  while [ "${#}" -gt 0 ] ; do
+    case "${1}" in
       "-c")
         shift
         if [ -z "${extra_c}" ]; then
@@ -233,9 +245,9 @@ EOF
         fi
 
         if [ -n "${vimcatrc}" ]; then
-          $vim -N -E -R -i NONE -u "${vimcatrc}" --cmd "visual | ${extra_cmd}" -c "set bg=dark fdl=9999 | syn enable | hi Normal ctermbg=NONE | silent! source ${script} | ${extra_c} | call AnsiHighlight(\"${dest_file}\", \"${line_numbers}\") | q" -- "${file}" </dev/tty >/dev/null 2>&1
+          $vim -N -E -s -i NONE -n -u "${vimcatrc}" --cmd "visual | ${extra_cmd}" -c "set bg=dark fdl=9999 | syn enable | hi Normal ctermbg=NONE | silent! source ${script}" -c "set buftype=nowrite | ${extra_c} | call AnsiHighlight(\"${dest_file}\", \"${line_numbers}\") | qa!" -- "${file}" </dev/tty >/dev/null 2>&1
         else
-          $vim -N -E -R -i NONE                  --cmd "visual | ${extra_cmd}" -c "set bg=dark fdl=9999 | syn enable | hi Normal ctermbg=NONE | silent! source ${script} | ${extra_c} | call AnsiHighlight(\"${dest_file}\", \"${line_numbers}\") | q" -- "${file}" </dev/tty >/dev/null 2>&1
+          $vim -N -E -s -i NONE -n                  --cmd "visual | ${extra_cmd}" -c "set bg=dark fdl=9999 | syn enable | hi Normal ctermbg=NONE | silent! source ${script}" -c "set buftype=nowrite | ${extra_c} | call AnsiHighlight(\"${dest_file}\", \"${line_numbers}\") | qa!" -- "${file}" </dev/tty >/dev/null 2>&1
         fi
 
         if [ -z "${output_file}" -o "${output_file}" = "-" ]; then
@@ -270,9 +282,33 @@ EOF
 : endif
 : endif
 : endif
-: endwhile
+: endif
+: endif
+: endif
+: endif
+: endif
+: endif
+: endif
 : endif
 : endfor
+: endif
+: endif
+: endif
+: endif
+: endif
+: endif
+: endif
+: endif
+: endif
+: endif
+: endwhile
+: endif
+: endif
+: endfor
+: endif
+: endif
+: endif
+: endif
 
 " AnsiHighlight: Allows for marking up a file, using ANSI color escapes when
 " the syntax changes colors, for easy, faithful reproduction.
