add input streaming for vimcat #172
Implement a pipeline with split -b 4096 as the endpoint into a temp dir
for vimcat, with the viml reading chunks as needed and deleting from
the top to keep a window onto the stream.

This is a prototype for how vimpager will implement this as well,
although that will be a bit more complicated.

Other misc improvements:
- add VIMCAT_DEBUG env var to not silence vim when sourcing script and
  running highlight code
- allow '-' file specifier for stdin for vimcat and vimpager
- call quit 1 on trap in vimcat and vimpager
- display error if -o is used for more than one file
- use the same method to separate files in vimcat as in vimpager, with
  blank lines between the headers and files
- truncate output file with -o option
- update ChangeLogs and TODO

TODO:
- ./vimcat -o - file | head # hangs the terminal, need to figure out
  why and fix

diff --git a/vimcat b/vimcat
--- a/vimcat
+++ b/vimcat
@@ -29,8 +29,27 @@
   fi
 
 quit() {
-  rm -rf "$tmp_dir"
+  (
+    kill "$vim_pid" >/dev/null 2>&1
+    do_sleep 100
+    kill -9 "$vim_pid" >/dev/null 2>&1
+
+    kill "$pipeline_pid" >/dev/null 2>&1
+    do_sleep 100
+    kill -9 "$pipeline_pid" >/dev/null 2>&1
+
+    kill "$tail_pid" >/dev/null 2>&1
+    do_sleep 100
+    kill -9 "$tail_pid" >/dev/null 2>&1
+
+    rm -rf "$tmp_dir"
+  ) &
   exit "$@"
+}
+
+do_sleep() {
+  _ms="${1:-100}"
+  "$vim" -NEsnR -i NONE -u NONE +"sleep $_ms m" +q >/dev/null 2>&1
 }
 
 usage() {
@@ -57,14 +76,46 @@ or available locally via: [32mman [1;35mvimcat[0m
 EOF
 }
 
-start_highlight_job() {
-  set -- -N -E -i NONE -n --cmd "visual | $extra_cmd" -c "set bg=dark fdl=9999 | syn enable | hi Normal ctermbg=NONE | silent! source $script" -c "set buftype=nowrite | $extra_c | call AnsiHighlight(\"$dest_file\", \"$line_numbers\") | qa!"
+write_chunks() {
+  cd "$chunks_dir"
+  rm -f -- *
+  split -b 4096 -
+  touch PIPELINE_DONE
+}
 
-  if [ -n "$vimcatrc" ]; then
-    set -- "$@" -u "$vimcatrc"
+start_pipeline() {
+  if [ -n "$pipeline" ]; then
+    pipeline="$pipeline | write_chunks"
+  else
+    pipeline=write_chunks
+  fi
+  cat -- "$pipeline_start" | (eval "$pipeline" <&3 & echo $! > "$tmp_dir/pipeline_pid") 3<&0
+  pipeline_pid="$(cat "$tmp_dir/pipeline_pid")"
+}
+
+start_highlight_job() {
+  _quit='qa!' _silent='silent!'
+  if [ "${VIMCAT_DEBUG:-0}" -ne 0 ]; then
+    _quit=echo _silent=
   fi
 
-  "$vim" "$@" -- "$file" </dev/tty >/dev/null 2>&1
+  set -- -NE -i NONE -n --cmd "visual | ${extra_cmd:-echo}" -c "silent! execute 'file ' . fnameescape('$pipeline_start') | set bg=dark fdl=9999 | syn enable | hi Normal ctermbg=NONE | $_silent source $script" -c "set buftype=nowrite | ${extra_c:-echo} | call AnsiHighlight(\"$dest_file\", ${line_numbers:-0}, \"$chunks_dir\") | $_quit"
+
+  [ -n "$vimcatrc" ] && set -- "$@" -u "$vimcatrc"
+
+  if [ "${VIMCAT_DEBUG:-0}" -eq 0 ]; then
+    "$vim" "$@" </dev/tty >/dev/null 2>&1 &
+  else
+    "$vim" "$@" </dev/tty
+  fi
+  vim_pid=$!
+}
+
+squeeze_blank_lines() {
+  sed '/^[ 	]*$/{
+    N
+    /^[ 	]*\n[ 	]*$/D
+  }'
 }
 
   # if no args and no stdin, display usage
@@ -104,7 +155,7 @@ start_highlight_job() {
     exit 1
   fi
 
-  trap 'rm -rf "$tmp_dir"' HUP INT QUIT ILL TRAP KILL BUS TERM
+  trap 'quit 1' PIPE HUP INT QUIT ILL TRAP KILL BUS TERM
   tmp_file_in="$tmp_dir/vimcat_in.txt"
   out_fifo="$tmp_dir/vimcat_out.fifo"
 
@@ -163,8 +214,11 @@ start_highlight_job() {
         shift
         break
         ;;
+      -)
+        break
+        ;;
       -*)
-        echo "$0: bad option '$1'"
+        echo "$0: bad option '$1', see --help for usage." >&2
         quit 1
         ;;
       *)
@@ -188,74 +242,73 @@ start_highlight_job() {
     fi
   fi
 
-  if [ -z "$extra_cmd" ]; then
-    extra_cmd='silent! echo'
-  fi
-
-  if [ -z "$extra_c" ]; then
-    extra_c='silent! echo'
-  fi
-
-  if [ -z "$line_numbers" ]; then
-    line_numbers=0
-  fi
-
   if [ $# -eq 0 ]; then
     set -- -
   fi
 
+  if [ -n "$output_file" -a $# -gt 1 ]; then
+    echo "$0: -o can only be used with one input file or stdin." >&2
+    quit 1
+  fi
+
+  chunks_dir="$tmp_dir/chunks"
+  mkdir "$chunks_dir"
+
+  i=1
   for file in "$@"
   do
     if [ $# -ge 2 ]; then
-      echo "==> $file <=="
-    fi
-
-    if [ "$file" = "-" ]; then
-      cat - >"$tmp_file_in"
-      file="$tmp_file_in"
-    fi
-
-    if [ "$squeeze_blank_lines" = "1" ]; then
-      cat -- "$file" > "$tmp_file_in.work"
-      sed -e '/^[ 	]*$/{
-				N
-				/^[ 	]*\n[ 	]*$/D
-      }' -- "$tmp_file_in.work" > "$tmp_file_in"
-      rm -f -- "$tmp_file_in.work"
-      file="$tmp_file_in"
-    fi
-
-    # Check that the file exists
-    if test -r "$file" -a -f "$file"; then
-      if test -s "$file"; then
-        if [ -z "$output_file" -o "$output_file" = "-" ]; then
-          dest_file="$out_fifo"
-        else
-          dest_file="$output_file"
-        fi
-
-        if [ -z "$output_file" -o "$output_file" = "-" ]; then
-          tail -f "$out_fifo" &
-          tail_pid=$!
-        fi
-
-        start_highlight_job
-
-        # if it's not a fifo where this doesn't work, tail needs some time to catch up
-        if [ ! -p "$out_fifo" ]; then
-          "$vim" -N -u NONE -Es +'sleep 1100 m' +q >/dev/null
-        fi
-
-        [ -n "$tail_pid" ] && kill $tail_pid
+      if [ $i -gt 1 ]; then
+        printf '\n'
       fi
-    else
-      echo "$0: Cannot read file: $file" >&2
+      printf "==> %s <==\n\n" "$file"
     fi
+
+    pipeline=
+    pipeline_start="$file"
+
+    if [ "${squeeze_blank_lines:-0}" -eq 1 ]; then
+      pipeline="squeeze_blank_lines"
+    fi
+
+    exit_code=0
+
+    # Check that the file is readable
+    if [ "$file" != - ]; then
+      if [ ! -r "$file" ]; then
+        echo "$0: Cannot read file: $file" >&2
+        exit_code=1
+      fi
+
+      [ ! -s "$file" ] && continue
+    fi
+
+    if [ -z "$output_file" -o "$output_file" = "-" ]; then
+      dest_file="$out_fifo"
+
+      tail -f "$out_fifo" &
+      tail_pid=$!
+    else
+      dest_file="$output_file"
+      printf '' > "$dest_file"
+    fi
+
+    start_highlight_job
+    start_pipeline
+    wait $vim_pid
+
+    if [ -n "$tail_pid" ]; then
+      # if it's not a fifo where this doesn't work, tail needs some time to catch up
+      [ ! -p "$out_fifo" ] && do_sleep 1100
+
+      kill $tail_pid >/dev/null 2>&1
+    fi
+
+    i=$((i + 1))
   done
 
-  quit 0
+  quit $exit_code
 
-: endif
 : endif
 : endif
 : endif
@@ -264,8 +317,6 @@ start_highlight_job() {
 : endif
 : endif
 : endfor
-: endif
-: endif
 : endif
 : endif
 : endif
@@ -278,6 +329,8 @@ start_highlight_job() {
 : endif
 : endif
 : endfor
+: endif
+: endif
 : endif
 : endif
 : endif
@@ -416,16 +469,84 @@ function! s:GroupToAnsi(groupnum)
   return retv
 endfunction
 
-function! AnsiHighlight(output_file, line_numbers)
-  filetype detect
-  syntax enable
-  syntaex sync minlines=500 maxlines=500
+function! s:ReadChunks()
+  let chunk_files = filter(glob(s:pipeline_dir . '/*', 1, 1), 'getfsize(v:val) > 0')
 
-  if a:line_numbers
+  if !len(chunk_files)
+    return 0
+  endif
+
+  call sort(chunk_files)
+
+  for chunk_file in chunk_files
+    let block = readfile(chunk_file, 'b')
+
+    let chunk_newline = 0
+
+    if block[-1] == ''
+      let chunk_newline = 1
+      call remove(block, -1)
+    endif
+
+    let lines = []
+
+    if line('$') == 1 && getline(1) == ''
+      let append_to = 0
+    else
+      if !s:chunk_newline
+        let lines = [ getline(line('$')) . remove(block, 0) ]
+        $d
+      endif
+
+      let append_to = line('$')
+    endif
+
+    let lines += block
+
+    call append(append_to, lines)
+
+    if append_to == 0
+      $d
+    endif
+
+    if s:chunk_num > 20
+      normal '0ggd/\_.\{4096}/e'
+    endif
+
+    let s:chunk_newline = chunk_newline
+
+    let s:chunk_num += 1
+  endfor
+
+  call map(chunk_files, 'delete(v:val)')
+
+  return 1
+endfunction
+
+function! AnsiHighlight(output_file, line_numbers, pipeline_dir)
+  let s:pipeline_dir = a:pipeline_dir
+
+  if a:pipeline_dir != ''
+    let s:chunk_num     = 1
+    let s:chunk_newline = 0
+
+    while !s:ReadChunks()
+      sleep 100 m
+    endwhile
+
+    let ln_field_len = 7
+  else
     let ln_field_len = len(line('$'))
   endif
 
-  for lnum in range(1, line('$'))
+  filetype detect
+  syntax enable
+  syntax sync minlines=500 maxlines=500
+
+  let done = 0
+  let lnum = 1
+
+  while !done
     let last = hlID('Normal')
     let output = s:GroupToAnsi(last) . "\<Esc>[K" " Clear to right
 
@@ -475,7 +596,36 @@ function! AnsiHighlight(output_file, line_numbers)
     endif
 
     call writefile([output . "\<Esc>[0m\r"], a:output_file, 'a')
-  endfor
+
+    let lnum += 1
+
+    if a:pipeline_dir == ''
+      if lnum > line('$')
+        let done = 1
+      endif
+    else
+      if lnum % 30 == 0
+        call s:ReadChunks()
+      endif
+
+      if lnum > line('$')
+        let stream_underrun = 1
+
+        while stream_underrun
+          let stream_underrun = !s:ReadChunks()
+
+          if stream_underrun
+            if filereadable(a:pipeline_dir . '/PIPELINE_DONE')
+              let done = 1
+              break
+            endif
+
+            sleep 100 m
+          endif
+        endwhile
+      endif
+    endif
+  endwhile
 
   return 1
 endfunction
