fix passthrough mode #11
Passthrough mode now preserves extra vim commands, like enabling man
page highlighting for small man pages and uses the filename when
available to choose a syntax as well.

Multiple -c and --cmd options are now supported in both vimpager and
vimcat, as well as the -u option for the .vimrc.

diff --git a/vimcat b/vimcat
--- a/vimcat
+++ b/vimcat
@@ -83,10 +83,40 @@
   # check for arguments to pass to vim
   while [ $# -gt 0 ] ; do
     case "${1}" in
-      "-c") shift; extra_c="${1}"; shift ;;
-      "--") shift; break ;;
-        -*) echo "bad option '${1}'" ; exit 1 ;;
-         *) break ;;
+      "-c")
+        shift
+        if [ -z "${extra_c}" ]; then
+          extra_c="${1}"
+        else
+          extra_c="${extra_c} | ${1}"
+        fi
+        shift
+        ;;
+      "--cmd")
+        shift
+        if [ -z "${extra_cmd}" ]; then
+          extra_cmd="${1}"
+        else
+          extra_cmd="${extra_cmd} | ${1}"
+        fi
+        shift
+        ;;
+      "-u")
+        shift
+        vimcatrc="${1}"
+        shift
+        ;;
+      "--")
+        shift
+        break
+        ;;
+      -*)
+        echo "${0}: bad option '${1}'"
+        exit 1
+        ;;
+      *)
+        break
+        ;;
     esac
   done
 
@@ -102,10 +132,12 @@
       echo "==> ${file} <=="
     fi
 
-    if [ -f ~/.vimcatrc ]; then
-        vimcatrc_arg="-u ~/.vimcatrc"
-    else
-        vimcatrc_arg=""
+    if [ -z "${vimcatrc}" ]; then
+      if [ -f ~/.vimcatrc ]; then
+          vimcatrc="~/.vimcatrc"
+      else
+          vimcatrc=""
+      fi
     fi
 
     if [ "${file}" = "-" ]; then
@@ -113,15 +145,31 @@
       file=${tmp_file}
     fi
 
+    if [ -z "${extra_cmd}" ]; then
+      extra_cmd='silent! echo'
+    fi
+
+    if [ -z "${extra_c}" ]; then
+      extra_c='silent! echo'
+    fi
+
     # Check that the file exists
     if test -r "${file}" -a -f "${file}"; then
       if test -s "${file}"; then
-        vim -E -X -R -i NONE $vimcatrc_arg -c "source ${script} | ${extra_c} | visual | call AnsiHighlight(\"${tmp_file}\") | q" -- "${file}" </dev/tty >/dev/null 2>&1
-        cat ${tmp_file}
-        echo
+        if [ -n "${vimcatrc}" ]; then
+          vim -E -X -R -i NONE -u "${vimcatrc}" --cmd "${extra_cmd}" -c "source ${script} | ${extra_c} | visual | call AnsiHighlight(\"${tmp_file}\") | q" -- "${file}" </dev/tty >/dev/null 2>&1
+        else
+          vim -E -X -R -i NONE                  --cmd "${extra_cmd}" -c "source ${script} | ${extra_c} | visual | call AnsiHighlight(\"${tmp_file}\") | q" -- "${file}" </dev/tty >/dev/null 2>&1
+        fi
+        cat "${tmp_file}"
+        # if file doesn't end in a newline, output a newline
+        last_char=$(tail -c 1 "${tmp_file}")
+        if [ "${last_char}" != "" ]; then
+          echo
+        fi
       fi
     else
-      echo "$0: Cannot read file: ${file}" >&2
+      echo "${0}: Cannot read file: ${file}" >&2
     fi
   done
 
@@ -129,8 +177,15 @@
 
   exit
 
-: endfor
+: endif
+: endif
+: endif
+: endif
+: endif
 : endwhile
+: endif
+: endfor
+: endif
 : endif
 : endif
 : endif
