Correct vimcat use for multiple input files
This allows "vimcat *" to work. It also adds a header ==>file<== when
there are multiple files (à la 'head'). Although this is significantly
different from 'cat' it seems good as we can't pipe the output of vimcat
to anything else anyway, so the extra adorment seems nice

diff --git a/vimcat b/vimcat
--- a/vimcat
+++ b/vimcat
@@ -9,13 +9,28 @@
 
   script=$(command -v ${0})
 
-  vim -E -X -R -c "source ${script} | visual | bufdo call AnsiHighlight(\"${tmp_file}\") | qa" "${@}" </dev/tty >/dev/null 2>&1
+  for file in "${@}"
+  do
+    if [ "${#}" -ge 2 ]
+    then
+      echo "==> ${file} <=="
+    fi
 
-  cat ${tmp_file}
+    # Check that the file exists
+    if test -r "${file}" -a -f "${file}"; then
+      vim -E -X -R -c "source ${script} | visual | call AnsiHighlight(\"${tmp_file}\") | q" "${file}" </dev/tty >/dev/null 2>&1
+      cat ${tmp_file}
+      echo
+    else
+      echo "vcat: Cannot read file: ${file}" >&2
+    fi
+  done
 
-  rm -f ${tmp_file}
+  rm -f "${tmp_file}"
 
   exit
+
+: endfor
 : endif
 
 " AnsiHighlight: Allows for marking up a file, using ANSI color escapes when
